### ISSUE TITLE
Maybe refactor away the wrappers from component.select.ts.

### ISSUE THREAD

**Issue by albatros13** [open-physiology/nested-resource-editor#11]
Update the components (Perhaps the ng select widgets are no longer buggy now)

**Comment by albatros13** [comment]
Tested with updated ng-select component - wrapper is still needed to distinguish internal selection update from external which prevents loop update when ng-select changes data and data change triggers update in the component selection fields.

**Comment by mhelvens** [comment]
Isn't a whole component wrapper kind of heavy machinery? I wonder if there isn't a much simpler solution.
